#!/usr/bin/python3
# -*- coding: utf-8 -*-

import json
import sys
import codecs

from IPython import embed


conn_in = 'conn_conv.json'

if len(sys.argv)>1:
    if sys.argv[1] == 'test':
        conn_in = 'conn_conv_test.json'
# load separated connections generated by process_json.py
connections = json.load(codecs.open(conn_in,'r'))


def by_port(port, conn=connections):
    port = str(port)
    for connection in conn:
        if connection[0]['_source']['layers']['tcp.port'][0] == port or connection[0]['_source']['layers']['tcp.port'][1] == port:
            return connection
embed()
